### ISSUE TITLE
Event on group label click

### ISSUE THREAD

**Issue by sadjehwty** [walkermatt/ol3-layerswitcher#38]
I have some nested layer groups.
I need to make visible all layers in subgroup when i click on group label.
I try to use jquery call $('.layer-switcher li.group>label').click(....); but when I click on label than handler wasn't fired.
What wrong?

**Comment by walkermatt** [comment]
Hi, It's probably due to the panel content being recreated each time the panel is shown. Try using https://api.jquery.com/on/ which is well suited to this situation as it allows you to add the listener to a parent element and have the handler function triggered when the event occurs on a child which matches a give selector. This works for me:

    jQuery('.layer-switcher').on('click', 'li.group>label', function() {console.log(this)});

**Comment by sadjehwty** [comment]
Thank you
